Add release process
dirty-cat/dirty_cat pull request #280
Opened 2022-07-05 15:06 UTC by LilianBoulard

A while ago, I wrote this little document, which describes the release process of dirty_cat.

I though it might be useful to add it for future contributors :)

2022-07-06 12:55 UTC, GaelVaroquaux commented
@jovan-stojanovic : can you review this. The question that you should be asking yourself is: is this clear enough for you to feel confident in doing a release?

2022-07-06 14:21 UTC, jovan-stojanovic requested changes

2022-07-06 14:21 UTC, jovan-stojanovic commented on RELEASE_PROCESS.md
> +   the version you're going to push (e.g. `0.1`)
Maybe adding the explicit commands here :
git commit -m "prepare for v1.0.0 release"
git tag v1.0.0
git push

2022-07-06 14:22 UTC, jovan-stojanovic commented on RELEASE_PROCESS.md
> +   the version you're going to push (e.g. `0.1`)
Otherwise, everything is good.

2022-07-06 14:37 UTC, jovan-stojanovic commented on RELEASE_PROCESS.md
> +
Maybe also add this to resources, may be useful:

[Managing releases in a repository](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)

2022-07-08 09:28 UTC, jovan-stojanovic approved these changes

2022-07-08 09:32 UTC, LilianBoulard commented
Thanks for the review, merging !

2022-07-08 09:32 UTC, merged