Make unnecessary API private
dirty-cat/dirty_cat pull request #331
Opened 2022-09-07 15:54 UTC by LilianBoulard

Fixes #315

2022-09-07 16:06 UTC, GaelVaroquaux commented
This is not necessary for release 0.3. We can move it to later.

2022-09-12 08:56 UTC, jovan-stojanovic approved these changes

2022-09-14 08:25 UTC, GaelVaroquaux requested changes
Only one comment: VERSION.txt should not be made private

2022-09-14 08:25 UTC, GaelVaroquaux commented on RELEASE_PROCESS.md
> +2. Update `dirty_cat/dirty_cat/_VERSION.txt` with the new version number
```suggestion
2. Update `dirty_cat/dirty_cat/VERSION.txt` with the new version number
```
I don't think that VERSION.text should be made private.

2022-09-14 08:25 UTC, GaelVaroquaux commented on dirty_cat/__init__.py
> +with open(_Path(__file__).parent / "_VERSION.txt") as _fh:
```suggestion
with open(_Path(__file__).parent / "VERSION.txt") as _fh:
```

2022-09-14 08:25 UTC, GaelVaroquaux commented on doc/conf.py
> +version_file = os.path.join('..', 'dirty_cat', '_VERSION.txt')
```suggestion
version_file = os.path.join('..', 'dirty_cat', 'VERSION.txt')
```

2022-09-14 08:25 UTC, GaelVaroquaux commented on setup.py
> +    os.path.dirname(__file__), 'dirty_cat', '_VERSION.txt')
```suggestion
    os.path.dirname(__file__), 'dirty_cat', 'VERSION.txt')
```

2022-09-14 08:25 UTC, GaelVaroquaux commented on setup.py
> +          package_data={'dirty_cat': ['_VERSION.txt']},
```suggestion
          package_data={'dirty_cat': ['VERSION.txt']},
```

2022-09-14 12:51 UTC, merged