DOC Ensures that DatetimeEncoder.fit passes numpydoc validation
dirty-cat/dirty_cat pull request #367
Opened 2022-09-15 20:02 UTC by alexdt1982

Addresses #345

2022-09-15 21:33 UTC, LilianBoulard requested changes

2022-09-15 21:33 UTC, LilianBoulard commented on dirty_cat/tests/test_docstrings.py
> +    #"dirty_cat._datetime_encoder.DatetimeEncoder.fit",
Could you please remove the line instead of commenting it?

2022-09-15 22:04 UTC, LilianBoulard approved these changes
Looks good to me! Thanks for the contribution, and welcome to the open-source community :)

2022-09-15 22:05 UTC, merged

2022-09-16 08:42 UTC, GaelVaroquaux commented
Thanks for the contribution, @alexdt1982 . It's great to see someone joining the wider open source community